cryptnox-sdk-esp32: ESP32Logger Class Reference
ESP32Logger Class Reference
#include <ESP32Logger.h>
Public Member Functions
bool begin (unsigned long baudRate=115200UL) override
void print (const __FlashStringHelper *str) override
void print (const char *str) override
void print (char c) override
void print (uint8_t value, int base=DEC) override
void print (uint16_t value, int base=DEC) override
void print (uint32_t value, int base=DEC) override
void print (int value, int base=DEC) override
void println () override
void println (const __FlashStringHelper *str) override
void println (const char *str) override
void println (char c) override
void println (uint8_t value, int base=DEC) override
void println (uint16_t value, int base=DEC) override
void println (uint32_t value, int base=DEC) override
void println (int value, int base=DEC) override
~ESP32Logger () override
Private Attributes
bool m_initialized = false
Detailed Description
ESP32 UART0 adapter implementing the CW_Logger interface.
Definition at line 20 of file ESP32Logger.h.
Constructor & Destructor Documentation
~ESP32Logger()
ESP32Logger::~ESP32Logger () inline override
Definition at line 57 of file ESP32Logger.h.
Member Function Documentation
begin()
bool ESP32Logger::begin (unsigned long baudRate = 115200UL) override
Initialise UART0 at the given baud rate; returns true on success.
Definition at line 84 of file ESP32Logger.cpp.
References m_initialized, UART_LOG_PORT, and UART_RX_FLOW_THRESH_NONE.
Referenced by app_main().
print() [1/7]
void ESP32Logger::print (char c) override
Print a single character.
Definition at line 115 of file ESP32Logger.cpp.
References m_initialized.
print() [2/7]
void ESP32Logger::print (const __FlashStringHelper * str) override
Print a PROGMEM string (treated as a RAM pointer on ESP32).
Definition at line 101 of file ESP32Logger.cpp.
References m_initialized, and uart_write_str().
Referenced by println(), println(), println(), println(), println(), println(), and println().
print() [3/7]
void ESP32Logger::print (const char * str) override
Print a NUL-terminated C string.
Definition at line 108 of file ESP32Logger.cpp.
References m_initialized, and uart_write_str().
print() [4/7]
void ESP32Logger::print (int value, int base = DEC) override
Print a signed integer in the given base; outputs a '-' prefix for negative decimals.
Definition at line 146 of file ESP32Logger.cpp.
References clamp_base(), m_initialized, and write_uint_to_uart().
print() [5/7]
void ESP32Logger::print (uint16_t value, int base = DEC) override
Print a 16-bit unsigned integer in the given base.
Definition at line 130 of file ESP32Logger.cpp.
References clamp_base(), m_initialized, and write_uint_to_uart().
print() [6/7]
void ESP32Logger::print (uint32_t value, int base = DEC) override
Print a 32-bit unsigned integer in the given base.
Definition at line 138 of file ESP32Logger.cpp.
References clamp_base(), m_initialized, and write_uint_to_uart().
print() [7/7]
void ESP32Logger::print (uint8_t value, int base = DEC) override
Print an 8-bit unsigned integer in the given base.
Definition at line 122 of file ESP32Logger.cpp.
References clamp_base(), m_initialized, and write_uint_to_uart().
println() [1/8]
void ESP32Logger::println () override
Print a CR+LF newline sequence.
Definition at line 162 of file ESP32Logger.cpp.
References LOGGER_NEWLINE, m_initialized, and uart_write_str().
Referenced by println(), println(), println(), println(), println(), println(), and println().
println() [2/8]
void ESP32Logger::println (char c) override
Print a single character followed by a newline.
Definition at line 181 of file ESP32Logger.cpp.
References print(), and println().
println() [3/8]
void ESP32Logger::println (const __FlashStringHelper * str) override
Print a PROGMEM string followed by a newline.
Definition at line 169 of file ESP32Logger.cpp.
References print(), and println().
println() [4/8]
void ESP32Logger::println (const char * str) override
Print a NUL-terminated C string followed by a newline.
Definition at line 175 of file ESP32Logger.cpp.
References print(), and println().
println() [5/8]
void ESP32Logger::println (int value, int base = DEC) override
Print a signed integer followed by a newline.
Definition at line 205 of file ESP32Logger.cpp.
References print(), and println().
println() [6/8]
void ESP32Logger::println (uint16_t value, int base = DEC) override
Print a 16-bit unsigned integer followed by a newline.
Definition at line 193 of file ESP32Logger.cpp.
References print(), and println().
println() [7/8]
void ESP32Logger::println (uint32_t value, int base = DEC) override
Print a 32-bit unsigned integer followed by a newline.
Definition at line 199 of file ESP32Logger.cpp.
References print(), and println().
println() [8/8]
void ESP32Logger::println (uint8_t value, int base = DEC) override
Print an 8-bit unsigned integer followed by a newline.
Definition at line 187 of file ESP32Logger.cpp.
References print(), and println().
Member Data Documentation
m_initialized
bool ESP32Logger::m_initialized = false private
Definition at line 60 of file ESP32Logger.h.
Referenced by begin(), print(), print(), print(), print(), print(), print(), print(), and println().
The documentation for this class was generated from the following files:
components/esp32_logger/include/ESP32Logger.h
components/esp32_logger/ESP32Logger.cpp