cryptnox-sdk-esp32: examples/UsdcSigning/main/eth_rlp.h File Reference
eth_rlp.h File Reference
#include <stdint.h>
#include <stddef.h>
Classes
struct eth_tx_t
Functions
size_t eth_rlp_encode_unsigned (const eth_tx_t *tx, uint8_t *out, size_t out_max)
size_t eth_rlp_encode_signed (const eth_tx_t *tx, uint8_t v, const uint8_t r[32], const uint8_t s[32], uint8_t *out, size_t out_max)
Function Documentation
eth_rlp_encode_signed()
size_t eth_rlp_encode_signed (const eth_tx_t * tx, uint8_t v, const uint8_t r[32], const uint8_t s[32], uint8_t * out, size_t out_max)
Definition at line 169 of file eth_rlp.cpp.
References encode_common_fields(), ITEMS_BUF_MAX, rlp_int256(), rlp_list_header(), and rlp_uint64().
Referenced by signing_loop().
eth_rlp_encode_unsigned()
size_t eth_rlp_encode_unsigned (const eth_tx_t * tx, uint8_t * out, size_t out_max)
Definition at line 152 of file eth_rlp.cpp.
References encode_common_fields(), ITEMS_BUF_MAX, and rlp_list_header().
Referenced by signing_loop().