cryptnox-sdk-esp32: components/pn532/include/pn532.h File Reference
pn532.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "driver/spi_master.h"
#include "driver/i2c_master.h"
Classes
struct pn532_config_t
struct pn532_t
Macros
#define PN532_MIFARE_ISO14443A (0x00U)
#define PN532_MAX_APDU_LEN (253U) /* max APDU bytes for pn532_send_apdu */
#define PN532_I2C_ADDRESS (0x24U)
Enumerations
enum pn532_transport_t { PN532_TRANSPORT_SPI , PN532_TRANSPORT_I2C }
Functions
esp_err_t pn532_init (pn532_t *dev, const pn532_config_t *config)
uint32_t pn532_get_firmware_version (pn532_t *dev)
bool pn532_sam_config (pn532_t *dev)
uint32_t pn532_read_passive_target_id (pn532_t *dev, uint8_t cardbaudrate)
bool pn532_send_apdu (pn532_t *dev, const uint8_t *apdu, uint8_t apdu_len, uint8_t *response, uint16_t *response_len)
bool pn532_release_target (pn532_t *dev)
Macro Definition Documentation
PN532_I2C_ADDRESS
#define PN532_I2C_ADDRESS (0x24U)
Definition at line 25 of file pn532.h.
Referenced by pn532_init_i2c().
PN532_MAX_APDU_LEN
#define PN532_MAX_APDU_LEN (253U) /* max APDU bytes for pn532_send_apdu */
Definition at line 22 of file pn532.h.
Referenced by pn532_send_apdu().
PN532_MIFARE_ISO14443A
#define PN532_MIFARE_ISO14443A (0x00U)
Definition at line 21 of file pn532.h.
Referenced by PN532Adapter::inListPassiveTarget(), and Pn532NfcTransport::inListPassiveTarget().
Enumeration Type Documentation
pn532_transport_t
enum pn532_transport_t
Enumerator
PN532_TRANSPORT_SPI
PN532_TRANSPORT_I2C
Definition at line 27 of file pn532.h.
Function Documentation
pn532_get_firmware_version()
uint32_t pn532_get_firmware_version (pn532_t * dev)
Definition at line 723 of file pn532.c.
References pn532_buffer_equal(), PN532_BYTE_SHIFT_BITS, PN532_CMD_TIMEOUT_MS, PN532_FIRMWARE_CMD_LEN, PN532_FIRMWARE_HDR_LEN, PN532_FIRMWARE_RESP_LEN, PN532_FIRMWAREVERSION, PN532_FW_IC_OFFSET, PN532_FW_REV_OFFSET, PN532_FW_SUPPORT_OFFSET, PN532_FW_VER_OFFSET, PN532_LOG_TAG, pn532_response_fw, read_data(), and send_command_check_ack().
Referenced by pn532_init(), PN532Adapter::printFirmwareVersion(), and Pn532NfcTransport::printFirmwareVersion().
pn532_init()
esp_err_t pn532_init (pn532_t * dev, const pn532_config_t * config)
Definition at line 662 of file pn532.c.
References pn532_get_firmware_version(), pn532_init_i2c(), pn532_init_spi(), PN532_LOG_TAG, pn532_sam_config(), PN532_SYNC_DELAY_MS, PN532_TRANSPORT_I2C, pn532_config_t::transport, and pn532_t::transport.
Referenced by app_main(), and PN532Adapter::begin().
pn532_read_passive_target_id()
uint32_t pn532_read_passive_target_id (pn532_t * dev, uint8_t cardbaudrate)
Definition at line 780 of file pn532.c.
References PN532_BYTE_SHIFT_BITS, PN532_CMD_TIMEOUT_MS, PN532_INLISTPASSIVETARGET, PN532_PASSIVE_CMD_LEN, PN532_PASSIVE_EXPECTED_TARGETS, PN532_PASSIVE_MAX_TARGETS, PN532_PASSIVE_NUM_TARGETS_OFFSET, PN532_PASSIVE_RESP_LEN, PN532_PASSIVE_UID_DATA_OFFSET, PN532_PASSIVE_UID_LEN_OFFSET, read_data(), and send_command_check_ack().
Referenced by PN532Adapter::inListPassiveTarget(), and Pn532NfcTransport::inListPassiveTarget().
pn532_release_target()
bool pn532_release_target (pn532_t * dev)
Definition at line 880 of file pn532.c.
References PN532_CMD_TIMEOUT_MS, PN532_EXCHANGE_STATUS_OFFSET, PN532_EXCHANGE_STATUS_OK, PN532_EXCHANGE_TG, PN532_INRELEASE, PN532_INRELEASE_CMD_LEN, PN532_INRELEASE_RESP_LEN, read_data(), and send_command_check_ack().
Referenced by PN532Adapter::resetReader(), and Pn532NfcTransport::resetReader().
pn532_sam_config()
bool pn532_sam_config (pn532_t * dev)
Definition at line 757 of file pn532.c.
References PN532_CMD_TIMEOUT_MS, PN532_SAM_CMD_LEN, PN532_SAM_NORMAL_MODE, PN532_SAM_RESP_CODE, PN532_SAM_RESP_CODE_OFFSET, PN532_SAM_RESP_LEN, PN532_SAM_TIMEOUT, PN532_SAM_USE_IRQ, PN532_SAMCONFIGURATION, read_data(), and send_command_check_ack().
Referenced by Pn532NfcTransport::begin(), and pn532_init().
pn532_send_apdu()
bool pn532_send_apdu (pn532_t * dev, const uint8_t * apdu, uint8_t apdu_len, uint8_t * response, uint16_t * response_len)
Definition at line 810 of file pn532.c.
References PN532_APDU_TIMEOUT_MS, PN532_EXCHANGE_CMD_OVERHEAD, PN532_EXCHANGE_DATA_OFFSET, PN532_EXCHANGE_FRAME_MAX, PN532_EXCHANGE_LEN_BIAS, PN532_EXCHANGE_LEN_OFFSET, PN532_EXCHANGE_STATUS_OFFSET, PN532_EXCHANGE_STATUS_OK, PN532_EXCHANGE_TG, PN532_EXT_EXCHANGE_DATA_OFFSET, PN532_EXT_EXCHANGE_ERR_OFFSET, PN532_EXT_FRAME_INDICATOR, PN532_EXT_FRAME_LENHI_OFFSET, PN532_EXT_FRAME_LENLO_OFFSET, PN532_INDATAEXCHANGE, PN532_LOG_TAG, PN532_MAX_APDU_LEN, read_data_apdu_frame(), and send_command_check_ack().
Referenced by PN532Adapter::sendAPDU(), Pn532NfcTransport::sendAPDU(), PN532Adapter::sendAPDULarge(), and Pn532NfcTransport::sendAPDULarge().