cryptnox-sdk-esp32: examples/UsdcSigning/main/main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <inttypes.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/spi_master.h"
#include "driver/gpio.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "CryptnoxWallet.h"
#include "Pn532NfcTransport.h"
#include "ESP32Logger.h"
#include "esp32_crypto_provider.h"
#include "ESP32Platform.h"
#include "pn532.h"
#include "keccak256.h"
#include "eth_rlp.h"
#include "eth_rpc.h"
#include "config.h"
Macros
#define PN532_USE_I2C 1
#define PN532_I2C_PORT 0 /* I2C_NUM_0 */
#define PN532_SDA 27 /* CN1 SDA */
#define PN532_SCL 22 /* CN1 SCL */
#define PN532_IRQ (-1) /* unused */
#define PN532_RST (-1) /* unused — drain in pn532_init handles soft-reboot recovery */
#define PN532_I2C_HZ 100000U
#define TX_BUF_SIZE 300U
Functions
static void parse_address (const char *hex, uint8_t out[20])
static void build_usdc_calldata (uint8_t out[68], const char *to_hex, uint64_t amount)
static void signing_loop (CryptnoxWallet &wallet)
void app_main (void)
Variables
static const char *const TAG = "usdc_signing"
static const uint8_t TRANSFER_SELECTOR [4] = { 0xa9U, 0x05U, 0x9cU, 0xbbU }
Macro Definition Documentation
PN532_I2C_HZ
#define PN532_I2C_HZ 100000U
Definition at line 47 of file main.cpp.
Referenced by app_main().
PN532_I2C_PORT
#define PN532_I2C_PORT 0 /* I2C_NUM_0 */
Definition at line 42 of file main.cpp.
Referenced by app_main().
PN532_IRQ
#define PN532_IRQ (-1) /* unused */
Definition at line 45 of file main.cpp.
Referenced by app_main().
PN532_RST
#define PN532_RST (-1) /* unused — drain in pn532_init handles soft-reboot recovery */
Definition at line 46 of file main.cpp.
Referenced by app_main().
PN532_SCL
#define PN532_SCL 22 /* CN1 SCL */
Definition at line 44 of file main.cpp.
Referenced by app_main().
PN532_SDA
#define PN532_SDA 27 /* CN1 SDA */
Definition at line 43 of file main.cpp.
Referenced by app_main().
PN532_USE_I2C
#define PN532_USE_I2C 1
Definition at line 38 of file main.cpp.
TX_BUF_SIZE
#define TX_BUF_SIZE 300U
Definition at line 62 of file main.cpp.
Referenced by signing_loop().
Function Documentation
app_main()
void app_main (void)
Definition at line 254 of file main.cpp.
References ADDR_FROM, ESP32Logger::begin(), eth_rpc_init(), eth_rpc_set_auth(), eth_rpc_wifi_connect(), pn532_config_t::i2c_clock_hz, pn532_config_t::i2c_port, NFC_CS, pn532_config_t::pin_cs, pn532_config_t::pin_irq, pn532_config_t::pin_rst, pn532_config_t::pin_scl, pn532_config_t::pin_sda, PN532_I2C_HZ, PN532_I2C_PORT, pn532_init(), PN532_IRQ, PN532_RST, PN532_SCL, PN532_SDA, PN532_TRANSPORT_I2C, PN532_TRANSPORT_SPI, RPC_URL, signing_loop(), pn532_config_t::skip_bus_init, pn532_config_t::spi_host, SPI_MAX_TRANSFER_SZ, SPI_MISO, SPI_MOSI, SPI_PIN_UNUSED, SPI_SCLK, TAG, pn532_config_t::transport, WIFI_PASSWORD, and WIFI_SSID.
build_usdc_calldata()
void build_usdc_calldata (uint8_t out[68], const char * to_hex, uint64_t amount) static
Definition at line 95 of file main.cpp.
References parse_address(), and TRANSFER_SELECTOR.
Referenced by signing_loop().
parse_address()
void parse_address (const char * hex, uint8_t out[20]) static
Definition at line 72 of file main.cpp.
Referenced by build_usdc_calldata(), and signing_loop().
signing_loop()
void signing_loop (CryptnoxWallet & wallet) static
Definition at line 118 of file main.cpp.
References ADDR_TO, ADDR_USDC, AMOUNT_USDC, build_usdc_calldata(), eth_tx_t::calldata, eth_tx_t::calldata_len, CARD_PIN, CARD_PIN_LEN, eth_tx_t::chain_id, CHAIN_ID_SEPOLIA, eth_rlp_encode_signed(), eth_rlp_encode_unsigned(), eth_rpc_ecrecover_parity(), eth_rpc_get_nonce(), eth_rpc_send_raw_tx(), eth_tx_t::eth_value, eth_tx_t::gas_limit, GAS_LIMIT_ERC20, keccak256(), MAX_FEE, eth_tx_t::max_fee, MAX_PRIORITY_FEE, eth_tx_t::max_priority_fee, eth_tx_t::nonce, parse_address(), TAG, eth_tx_t::to, and TX_BUF_SIZE.
Referenced by app_main().
Variable Documentation
TAG
const char* const TAG = "usdc_signing" static
Definition at line 33 of file main.cpp.
TRANSFER_SELECTOR
const uint8_t TRANSFER_SELECTOR[4] = { 0xa9U, 0x05U, 0x9cU, 0xbbU } static
Definition at line 59 of file main.cpp.
Referenced by build_usdc_calldata().